load("//tools:mtidd.bzl", "mtidd_test")

mtidd_test(
    name = "internalizer_tests",
)

mtidd_test(
    name = "interval_tests",
)

mtidd_test(
    name = "lattice_tests",
)

mtidd_test(
    name = "cache_tests",
)

mtidd_test(
    name = "mtidd_tests",
)

mtidd_test(
    name = "partition_iterator_tests",
)

mtidd_test(
    name = "partition_tests",
)
