load("//tools:mtidd.bzl", "mtidd_test")

cc_library(
    name = "mtidd",
    srcs = [
        "interval.cpp",
        "lattice.cpp",
        "utils.cpp",
        "internalizer.h",
        "interval.h",
        "lattice.h",
        "partition.h",
        "partition_iterator.h",
        "utils.h",
    ],
    hdrs = [
        "mtidd.h",
    ],
    visibility = ["//visibility:public"],
)

