load("//tools:mtidd.bzl", "mtidd_test")

cc_library(
    name = "mtidd",
    srcs = [
        "interval.cpp",
        "lattice.cpp",
        "utils.cpp",
        "internalizer.hpp",
        "interval.hpp",
        "lattice.hpp",
        "partition.hpp",
        "partition_iterator.hpp",
        "utils.hpp",
        "cache.hpp",
    ],
    hdrs = [
        "mtidd.hpp",
    ],
    visibility = ["//visibility:public"],
)

