// Settings from CMake
#define MTIDD_VERSION_MAJOR @MTIDD_VERSION_MAJOR@
#define MTIDD_VERSION_MINOR @MTIDD_VERSION_MINOR@
#define MTIDD_VERSION_PATCH @MTIDD_VERSION_PATCH@
#define PACKAGE_STRING      "@PACKAGE_STRING@"
#define PACKAGE_VERSION     "@PACKAGE_VERSION@"
